version: "3"
services:
  app:
    image: my/rails:latest
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DATABSE_URL=mysql://root@localhost:3306/test
      - PORT=4001
      - RAILS_MASTER_KEY=15747a55419641bbb119c134451c4225
      - SECURE_KEY_BASE=645d22504ac8e152ef855038c0b59e9e94662db0b5a6b6532668ee80699755898e8433bbb2d2826f05e46e51d1d9097925282087d1e7ba4ff512a393741c96e5
    ports:
      - "4001:4001"
    volumes:
      - ./vendor/public/assets:/home/app/rails-app/public/assets
    command: bundle exec rails s
